---
title: "Messenger_1"
author: "Bartosz Dąbrowski"
date: "4 05 2020"
output: html_document
---

```{r}
library(jsonlite)
library(lubridate)
library(tidyverse)
library(tidytext)
library(stringi)
library(tm)
library(qdapRegex)
library(wordcloud)
library(viridisLite)
library(gganimate)
library(zoo)
library(circular)
```


```{r}
data1<-jsonlite::fromJSON(txt='E:/data18052020/messages/inbox/Jakbedziewdomusekcjazakazna_HYr4iyYDqA/data1.txt')
data2<-jsonlite::fromJSON(txt='E:/data18052020/messages/inbox/Jakbedziewdomusekcjazakazna_HYr4iyYDqA/data2.txt')
data3<-jsonlite::fromJSON(txt='E:/data18052020/messages/inbox/Jakbedziewdomusekcjazakazna_HYr4iyYDqA/data3.txt')
data4<-jsonlite::fromJSON(txt='E:/data18052020/messages/inbox/Jakbedziewdomusekcjazakazna_HYr4iyYDqA/data4.txt')
data5<-jsonlite::fromJSON(txt='E:/data18052020/messages/inbox/Jakbedziewdomusekcjazakazna_HYr4iyYDqA/data5.txt')
data6<-jsonlite::fromJSON(txt='E:/data18052020/messages/inbox/Jakbedziewdomusekcjazakazna_HYr4iyYDqA/data6.txt')
data7<-jsonlite::fromJSON(txt='E:/data18052020/messages/inbox/Jakbedziewdomusekcjazakazna_HYr4iyYDqA/data7.txt')
data8<-jsonlite::fromJSON(txt='E:/data18052020/messages/inbox/Jakbedziewdomusekcjazakazna_HYr4iyYDqA/data8.txt')
data9<-jsonlite::fromJSON(txt='E:/data18052020/messages/inbox/Jakbedziewdomusekcjazakazna_HYr4iyYDqA/data9.txt')
data10<-jsonlite::fromJSON(txt='E:/data18052020/messages/inbox/Jakbedziewdomusekcjazakazna_HYr4iyYDqA/data10.txt')
data11<-jsonlite::fromJSON(txt='E:/data18052020/messages/inbox/Jakbedziewdomusekcjazakazna_HYr4iyYDqA/data11.txt')
data12<-jsonlite::fromJSON(txt='E:/data18052020/messages/inbox/Jakbedziewdomusekcjazakazna_HYr4iyYDqA/data12.txt')
```



```{r}
data_msg_comb<-rbind(data1$messages[1:3],data2$messages[1:3],data3$messages[1:3],data4$messages[1:3],data5$messages[1:3],data6$messages[1:3],data7$messages[1:3],data8$messages[1:3],data9$messages[1:3],data10$messages[1:3],data11$messages[1:3],data12$messages[1:3])

#data_msg_comb<-data1$messages[1:3] 
options(digits.secs=6)
data_msg_comb[,2]<-as.POSIXct(as.vector(data_msg_comb[,2])/1000,origin=lubridate::origin)

str(data_msg_comb)
```

```{r}
df1<-tidyr::separate(data_msg_comb,col=timestamp_ms,
           into=c('Date','Time'),
           sep=" ")
```







```{r}
#df2<-df1[-c(974:977),]
df2<-df2%>%
  group_by(Date)%>%
  count(content)
df2$Date=as.POSIXct(df2$Date)
```

```{r}
ggplot(df2, aes(x=Date,y=n))+
  geom_col(color='coral2')+
  scale_x_datetime(date_breaks="2 months",date_labels="%m %Y")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  ggtitle('Wiadomości')+
  theme(plot.title = element_text(hjust = 0.5))+
  xlab('')+
  ylab('Wiadomości')
```

```{r}
df8<-data_msg_comb
df8$timestamp_ms<-format(df8$timestamp_ms,format='%Y-%m-%d %H:%M')
df8<-tidyr::separate(df8,col=timestamp_ms,
           into=c('Date','Time'),
           sep=" ")


```

```{r}
df9<-df8
df9$Time<-as.POSIXct(df9$Time,format='%H')
df9<-df9%>%
  group_by(Time)%>%
  count(content)
```


```{r}
ggplot(df9, aes(x=Time,y=n))+
  geom_col()+
  scale_x_datetime(date_breaks="1 hour",date_labels="%H")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  ggtitle('Godziny')+
  theme(plot.title = element_text(hjust = 0.5))+
  xlab('')+
  ylab('Wiadomości')
```


```{r}
ggplot(df9, aes(x = hour(Time))) + geom_histogram(bins=24,breaks = seq(0, 
    24),  fill = "chartreuse3",colour='white') +  theme_minimal() + 
    scale_fill_brewer() + ylab("Wiadomości") + ggtitle("Godziny") +
  theme(plot.title = element_text(hjust = 0.5))+
    scale_x_continuous("", limits = c(0, 24), breaks = seq(0, 24), labels = seq(0, 
        24))
```


```{r}
df3<-data_msg_comb%>%
  group_by(sender_name)%>%
  count(content)
  
ggplot(df3,aes(x=reorder(sender_name,-n),y=n))+
  geom_col()+
  coord_flip()+
  xlab('')+
  ylab('Wiadomości')

```


```{r}
data_text<-data_msg_comb%>%
  tibble::rowid_to_column("doc_id")
data_text<-data_text[,c('doc_id','content','sender_name','timestamp_ms')]
colnames(data_text)<-c('doc_id','text','sender_name','timestamp_ms')
#data_short<-data_text #for convenience
data_short<-data_text[1:15000,]
```



```{r}
#emoji<-read_xlsx('E:/asd/emoticon_conversion.xlsx')
#colnames(emoji)<-c('a','b','c','d','e','f','g','Unicode','Bytes','Description')
#data_no_emoji$text<-removeWords(data_no_emoji$text,emoji$Bytes)
```



```{r}
data_no_emoji<-data_short
data_no_emoji$text<-rm_url(data_no_emoji$text)
data_no_emoji$text<-gsub("[^A-Za-zĄąćĆĘęŁłŃńóÓŚśŻżŹź0-9]"," ",data_no_emoji$text)
unwanted_array = list('Ą'="A",'ą'='a','ć'='c','Ć'='C','Ę'='E','ę'='e','Ł'='L','ł'='l','Ń'="N",'ń'='n','ó'='o','Ó'='O','Ś'='S','ś'='s','Ż'='Z','ż'='z','ź'='z','Ź'='Z')
data_no_emoji$text<-chartr(paste(names(unwanted_array), collapse=''),
         paste(unwanted_array, collapse=''),
         data_no_emoji$text)
nanotek<-dplyr::filter(data_short, grepl('ejj', text))



#nanotek<-dplyr::filter(data_no_emoji, grepl('bartosz', text))
#custom_stop<-c('nanotek','you','your','call','chat','theme','the','called','missed','sent','nickname','has','turned','played','tez','wiec','bym','now','mial','mialem',,'miec','maja','masz','turn','attachment','kuba','bartosz')
custom_stop<-c('tez','bym','maja','wie','zalacznik','miec','chociaz','wiec','chyba','jakies','raczej','troche')
```

```{r}
wek<-c('mysle','myslalem','myslalam','myslec','Mysle','Myslalem','Myslalam','Myslec')
data_no_emoji$text<-gsub(paste(wek, collapse = '|'), 'mysle', data_no_emoji$text)
wek<-c('galeria','galerii','Galerii','Galeria')
data_no_emoji$text<-gsub(paste(wek, collapse = '|'), 'galeria', data_no_emoji$text)
wek<-c('wiesz','wiem','wiedziec','Wiesz','Wiem')#,'wiedzialem','wiedzialam')
data_no_emoji$text<-gsub(paste(wek, collapse = '|'), 'wiem', data_no_emoji$text)
wek<-c('czasu','czasie','czas')
data_no_emoji$text<-gsub(paste(wek, collapse = '|'), 'czas', data_no_emoji$text)
wek<-c('hej','hej','hejoo')
data_no_emoji$text<-gsub('chwile', 'chwila', data_no_emoji$text)
```

```{r}
data_source<-DataframeSource(data_no_emoji)
data_corpus<-VCorpus(data_source)
data_corpus
```

```{r}
stopwords <- read_csv("E:/asd/polish.stopwords.txt", 
    col_names = FALSE)
head(stopwords)
```

```{r}
data_clean<-tm_map(data_corpus,removePunctuation)
data_clean<-tm_map(data_clean, content_transformer(tolower))
data_clean<-tm_map(data_clean,stripWhitespace)
data_clean<-tm_map(data_clean,removeWords,stopwords$X1)
data_clean<-tm_map(data_clean,removeWords,custom_stop)
```


#there's a problem with emoji
NO MORE :)
```{r}
data_tdm<-TermDocumentMatrix(data_clean)
data_tdm
```

```{r}
gc()
data_m<-as.matrix(data_tdm)
dim(data_m)
```

```{r}
freq <- rowSums(data_m)
freq <- sort(freq,decreasing=TRUE)
```


```{r}
str(freq)
head(freq,35)
barplot(freq[1:10], col = "tan", las = 2)
```


```{r}
layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, "Co mówią Fani?")
wordcloud(names(freq),freq,max.words=35,color=plasma(1),main='Title')
```

```{r}
df4<-df1[,-3]

df4<-df4%>%
  mutate(counter=1)

df4<-df4%>%
  complete(sender_name,Date) 
```

```{r}
df4[is.na(df4)]<-0
df5<-df4%>%
  group_by(sender_name,Date)%>%
  summarize(counter=sum(counter))
```

```{r}
set.seed(21)
df6<-df5 %>%
  arrange(sender_name,Date)%>%
  group_by(sender_name)%>%
  #aggregate(df3$Scrobbles_mo, by=list(c(Artist,Date)), sum)
  mutate(Cumsum=cumsum(counter)+runif(1,0,0.00000001), #prevent from overlappping bars with same height
         Cumsum_formatted=formatC(Cumsum,0,format="f"))#prevent from displaying values like 31.0000032932093 scrobbles
```


```{r}
#str(df6)
df7<-df6%>%
  group_by(Date)%>%
  mutate(Rank=rank(-Cumsum))%>%
  #mutate(Cumsum_rel = Cumsum/Cumsum[Rank==1])%>%
  #group_by(sender_name)%>%
  #filter(Rank<=10)%>%
  ungroup()
```


```{r}
  staticplot = ggplot(df7, aes(Rank, group = sender_name, 
                                       fill = as.factor(sender_name), color = as.factor(sender_name)))+
  geom_tile(aes(y = Cumsum/2,
                height = Cumsum,
                width = 0.9), alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(sender_name, " ")), vjust = 0.2, hjust = 1) +
  geom_text(aes(y=Cumsum,label = Cumsum_formatted, hjust=0)) +#label do korekty ew.
  coord_flip(clip = "off", expand = FALSE) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        legend.position="none",
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.grid.major.x = element_line( size=.1, color="grey" ),
        panel.grid.minor.x = element_line( size=.1, color="grey" ),
        plot.title=element_text(size=25, hjust=0.5, face="bold", colour="grey", vjust=-1),
        plot.subtitle=element_text(size=18, hjust=0.5, face="italic", color="grey"),
        plot.caption =element_text(size=8, hjust=0.5, face="italic", color="grey"),
        plot.background=element_blank(),
        plot.margin = margin(2,2, 2, 4, "cm"))
```  


```{r}  
  animated = staticplot + transition_states(Date, transition_length = 4, state_length = 2) +
    view_follow(fixed_x = TRUE)  +
    labs(title = 'Bukawka {closest_state}',  
         subtitle  =  "Najwięksi spamerzy",
         caption  = "Aktywność")
```



```{r}
#  animate(animated, 1400, fps = 20,  width = 1200, height = 1000, 
  #        renderer = gifski_renderer("gganim.gif"))
  
  video<-animate(animated, 2000, fps = 25,  width = 1200, height = 1000,
          renderer = ffmpeg_renderer())
  anim_save("top_spamers2.mp4", animation = video)
```